### ISSUE TITLE
need autocell.h/.cpp

### ISSUE THREAD

**Issue by pvthuyet** [JamesBremner/stackoverflow75410318#2]
Hi @JamesBremner , 
Thank you for your sharing,
Could you please add the autocell.h/.cpp ?

**Comment by JamesBremner** [comment]
https://github.com/JamesBremner/autocell/tree/main/src

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/stackoverflow75410318/assets/2046227/9f47e8c1-4067-43d9-8b7a-ab88ab9fdc4b)

**Comment by JamesBremner** [comment]
I see the problem.  The autocell repo is private.

**Comment by JamesBremner** [comment]
You should be able to see the code now.

**Comment by pvthuyet** [comment]
Thank you James,
I got it
