### ISSUE TITLE
Same cell chosen twice

### ISSUE THREAD

**Issue by pvthuyet** [JamesBremner/stackoverflow75410318#3]
I run with multiple sequences data.
![image](https://github.com/JamesBremner/stackoverflow75410318/assets/1078056/4554dc28-ae79-490c-aa39-8f8fd68a9ed7)

and got result:

```
Searching
3A 3A 10 9B 72
9B 72 3A 10 72
10 3A 3A 3A 10
3A 10 3A 9B 72
10 10 3A 72 72

for sequence 9B 3A

row 0 col 3 9B
row 2 col 3 3A

for sequence 10 10 3A

Cannot find sequence starting in 1st row, using wasted moves
WM 0 0
row 2 col 0 10
row 2 col 0 10
row 2 col 1 3A
```

This is not expected result.
Please kindly check.

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/stackoverflow75410318/assets/2046227/4a1f4313-54cd-48de-b95f-5d3bb8420fe8)

**Comment by pvthuyet** [comment]
But in this case the expected result is
```
row 0 col 3 9B
row 2 col 3 3A
row 2 col 0 10
row 4 col 0 10
row 4 col 2 3A
```

**Comment by pvthuyet** [comment]
Please note that the RED line is expected result
